- name: check data types
  hosts: localhost
  vars:
    NAME: Shivakumar # key value
    SKILLS: # Skills in list type
      - Devops
      - ShellScript
      - Docker
      - Linus
    Experience: # Expericen is map type. It contains key value pairs
      Devops: 7
      Docker: 4
      Linux: 2
    Trainer: true # boolean
  tasks:
    - name: Print key value pair
      ansible.builtin.debug:
        msg: "Name of the person: {{NAME}}"
    - name: Print list
      ansible.builtin.debug:
        msg: "Skills are : {{SKILLS}}"
    - name: Print map
      ansible.builtin.debug:
        msg: "Experience: {{Experience}}"
    - name: Print bulean
      ansible.builtin.debug:
        msg: "Is he trainer: {{Trainer}}"     
