- name: check condition
  hosts: localhost
  tasks:
    - name: check roboshop user is exist or not
      ansible.builtin.command: id roboshop
      register: user
    
    - name: print roboshop user
      ansible.builtin.debug:
        msg: " User output name:  {{user}} "