- name: check condition
  hosts: localhost
  tasks:
    - name: check roboshop user is exist or not
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true
    
    - name: print variable value
      ansible.builtin.debug:
        msg: "User output name:  {{user}} "
    
    - name: print exit status or return code
      ansible.builtin.debug:
        msg: "Exit status is : {{user.rc}}"