- name: checking loops
  hosts: localhost
  become: yes
  tasks:
    - name: print names
      ansible.inbultin.debug:
        msg: "Hello {{item}}"
      loops:
        - ramesh
        - rakesh
        - suresh
        - mukesh