- name: check condition
  hosts: localhost
  tasks:
    - name: check user
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true

    - name: print user output
      ansible.builtin.debug:
        msg: "user output is {{user}}"
