- name: check condition
  hosts: localhost
  tasks:
    - name: check user
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true

    - name: check user output
      ansible.builtin.debug:
        msg: "user output is {{user}}"
    
    - name: check exit status or return code
      ansible.builtin.debug:
        msg: "Exit status is {{user.rc}}"
    
    - name: create user
      ansible.builtin.user:
        name: roboshop
      when: user.rc != 0
    
